In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# TV Script Generation
In this project, you'll generate your own [Simpsons](https://en.wikipedia.org/wiki/The_Simpsons) TV scripts using RNNs.  You'll be using part of the [Simpsons dataset](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data) of scripts from 27 seasons.  The Neural Network you'll build will generate a new TV script for a scene at [Moe's Tavern](https://simpsonswiki.com/wiki/Moe's_Tavern).
## Get the Data
The data is already provided for you.  You'll be using a subset of the original dataset.  It consists of only the scenes in Moe's Tavern.  This doesn't include other versions of the tavern, like "Moe's Cavern", "Flaming Moe's", "Uncle Moe's Family Feed-Bag", etc..

In [3]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper

data_dir = '/media/nobu/UbuntuFiles/statsProject/lyrics/2pac.txt'#'moes_tavern_lines.txt'
text = helper.load_data(data_dir)
# Ignore notice, since we don't use it for analysing the data
text = text[81:]
print(text)

rfucker!
 West Side, Bad Boy killas
 You know who the realest is
 We bring it too
First off, fuck yo' bitch and the clique you claim
Westside when we ride, come equipped with game
You claim to be a player, but I fucked your wife
We bust on Bad Boys, niggas fucked for life
Plus, Puffy tryna see me, weak hearts I rip
Biggie Smalls and Junior M.A.F.I.A. some mark-ass bitches
We keep on comin' while we runnin' for your jewels
Steady gunnin', keep on bustin' at them fools, you know the rules
Lil' Caesar, go ask your homie how I'll leave ya
Cut your young-ass up, leave you in pieces, now be deceased
Lil' Kim, don't fuck around with real Gs
Quick to snatch yo' ugly ass off the streets, so fuck peace!
I'll let them niggas know it's on for life
Don't let the Westside ride tonight 
Bad Boy murdered on wax and killed
Fuck with me and get yo' caps peeled, you know
See, grab your Glocks when you see 2Pac
Call the cops when you see 2Pac, uh
Who shot me? But you punks didn't finish
Now you 'bout to f

## Explore the Data
Play around with `view_sentence_range` to view different parts of the data.

In [4]:
#play with the range here
view_sentence_range = (0, 10)

"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import numpy as np

print('Dataset Stats')
print('Roughly the number of unique words: {}'.format(len({word: None for word in text.split()})))
scenes = text.split('\n\n')#two new lines indicate a new scene
print('Number of scenes: {}'.format(len(scenes)))
sentence_count_scene = [scene.count('\n') for scene in scenes]
print('Average number of sentences in each scene: {}'.format(np.average(sentence_count_scene)))

sentences = [sentence for scene in scenes for sentence in scene.split('\n')]
print('Number of lines: {}'.format(len(sentences)))
word_count_sentence = [len(sentence.split()) for sentence in sentences]
print('Average number of words in each line: {}'.format(np.average(word_count_sentence)))

print()
print('The sentences {} to {}:'.format(*view_sentence_range))
print('\n'.join(text.split('\n')[view_sentence_range[0]:view_sentence_range[1]]))



Dataset Stats
Roughly the number of unique words: 14845
Number of scenes: 1
Average number of sentences in each scene: 20276.0
Number of lines: 20277
Average number of words in each line: 8.286531538195986

The sentences 0 to 10:
rfucker!
 West Side, Bad Boy killas
 You know who the realest is
 We bring it too
First off, fuck yo' bitch and the clique you claim
Westside when we ride, come equipped with game
You claim to be a player, but I fucked your wife
We bust on Bad Boys, niggas fucked for life
Plus, Puffy tryna see me, weak hearts I rip
Biggie Smalls and Junior M.A.F.I.A. some mark-ass bitches


## Implement Preprocessing Functions
The first thing to do to any dataset is preprocessing.  Implement the following preprocessing functions below:
- Lookup Table
- Tokenize Punctuation

### Lookup Table
To create a word embedding, you first need to transform the words to ids.  In this function, create two dictionaries:
- Dictionary to go from the words to an id, we'll call `vocab_to_int`
- Dictionary to go from the id to word, we'll call `int_to_vocab`

Return these dictionaries in the following tuple `(vocab_to_int, int_to_vocab)`

In [5]:
import numpy as np
#import problem_unittests as tests
from collections import Counter
#assign ints ascending with 0 as most common (ie. the)
#import utils
#############################################

################################################
def create_lookup_tables(text):
    """
    Create lookup tables for vocabulary
    :param text: The text of tv scripts split into words
    :return: A tuple of dicts.  The first dict....
    """
    words = text #.split()#split text into individual words
    word_counts = Counter(words)
    sorted_vocab = sorted(word_counts, key=word_counts.get, reverse=True)
    int_to_vocab = {ii: word for ii, word in enumerate(sorted_vocab)}
    vocab_to_int = {word: ii for ii, word in int_to_vocab.items()}

    return (vocab_to_int, int_to_vocab)
    
    
#######################################################################################
#test code
#v_to_int, int_to_v = create_lookup_tables(text)
#print(v_to_int)
#print(int_to_v)

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_create_lookup_tables(create_lookup_tables)

"\nDON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE\n"

### Tokenize Punctuation
We'll be splitting the script into a word array using spaces as delimiters.  However, punctuations like periods and exclamation marks make it hard for the neural network to distinguish between the word "bye" and "bye!".

Implement the function `token_lookup` to return a dict that will be used to tokenize symbols like "!" into "||Exclamation_Mark||".  Create a dictionary for the following symbols where the symbol is the key and value is the token:
- Period ( . )
- Comma ( , )
- Quotation Mark ( " )
- Semicolon ( ; )
- Exclamation mark ( ! )
- Question mark ( ? )
- Left Parentheses ( ( )
- Right Parentheses ( ) )
- Dash ( -- )
- Return ( \n )

This dictionary will be used to token the symbols and add the delimiter (space) around it.  This separates the symbols as it's own word, making it easier for the neural network to predict on the next word. Make sure you don't use a token that could be confused as a word. Instead of using the token "dash", try using something like "||dash||".

In [6]:
def token_lookup():
    """
    Generate a dict to turn punctuation into a token.
    :return: Tokenize dictionary where the key is the punctuation and the value is the token
    """
    # TODO: Implement Function
    token_to_alpha={'.':'<PERIOD>', ',':'<COMMA>', 
                    '"':'QUOTATION_MARK',';':'SEMICOLON',
                   '!':'EXCLAMATION_MARK', '?':'QUESTION_MARK',
                    '(':'LEFT_PAREN', ')':'RIGHT_PAREN',
                   '--':'DDDAAASSSH', '\n':'RRRETTTURRRN'}
    
    
    return token_to_alpha
#########################################################
#import tensorflow as tf
#sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

#############################################################################


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_tokenize(token_lookup)#is returned to token_dict capture variable

"\nDON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE\n"

## Preprocess all the data and save it
Running the code cell below will preprocess all the data and save it to file.

In [7]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Preprocess Training, Validation, and Testing Data
helper.preprocess_and_save_data(data_dir, token_lookup, create_lookup_tables)

# Check Point
This is your first checkpoint. If you ever decide to come back to this notebook or have to restart the notebook, you can start from here. The preprocessed data has been saved to disk.

In [ ]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper
import numpy as np
#import problem_unittests as tests

int_text, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()

'''
print(int_text[:10])

first2pairs = {k: vocab_to_int[k] for k in list(vocab_to_int)[:2]}

print(first2pairs)
print(vocab_to_int[10])
print(token_dict[10])

for i in range(100):
    curr = int_text[i]
    #curr_word = vocab_to_int[i]
    print(int_to_vocab[i])
    #print(curr_word)
'''

'\nprint(int_text[:10])\n\nfirst2pairs = {k: vocab_to_int[k] for k in list(vocab_to_int)[:2]}\n\nprint(first2pairs)\nprint(vocab_to_int[10])\nprint(token_dict[10])\n\nfor i in range(100):\n    curr = int_text[i]\n    #curr_word = vocab_to_int[i]\n    print(int_to_vocab[i])\n    #print(curr_word)\n'

## Build the Neural Network
You'll build the components necessary to build a RNN by implementing the following functions below:
- get_inputs
- get_init_cell
- get_embed
- build_rnn
- build_nn
- get_batches

### Check the Version of TensorFlow and Access to GPU

In [ ]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from distutils.version import LooseVersion
import warnings
import tensorflow as tf

# Check TensorFlow Version
assert LooseVersion(tf.__version__) >= LooseVersion('1.0'), 'Please use TensorFlow version 1.0 or newer'
print('TensorFlow Version: {}'.format(tf.__version__))


# Check for a GPU
if not tf.test.gpu_device_name():
    warnings.warn('No GPU found. Please use a GPU to train your neural network.')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
    
!pip install tensorflow==1.0.0

### Input
Implement the `get_inputs()` function to create TF Placeholders for the Neural Network.  It should create the following placeholders:
- Input text placeholder named "input" using the [TF Placeholder](https://www.tensorflow.org/api_docs/python/tf/placeholder) `name` parameter.
- Targets placeholder
- Learning Rate placeholder

Return the placeholders in the following tuple `(Input, Targets, LearningRate)`

In [ ]:
def get_inputs():
    """
    Create TF Placeholders for input, targets, and learning rate.
    :return: Tuple (input, targets, learning rate)
    """
    # TODO: Implement Function
    #actually just need to make these, nothing complex like picking data to feed in
    # Declare placeholders we'll feed into the graph, use None for shape so can change later
    Input = tf.placeholder(tf.int32, [None, None], name='input')
    #targets is one word shifted over since we're trying to predict next word
    #targets=int_text[1:]
    #last word should be the first word?  
    #targets[-1]=int_text[0]
    Targets = tf.placeholder(tf.int32, [None, None], name='targets')
    
    #LearningRate placeholder
    LearningRate =tf.placeholder(tf.float32, [], name='LearningRate')
    
    
    return (Input, Targets, LearningRate)

###refer here: https://www.tensorflow.org/programmers_guide/tensors    


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_get_inputs(get_inputs)

### Build RNN Cell and Initialize
Stack one or more [`BasicLSTMCells`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell) in a [`MultiRNNCell`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell).
- The Rnn size should be set using `rnn_size`
- Initalize Cell State using the MultiRNNCell's [`zero_state()`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell#zero_state) function
    - Apply the name "initial_state" to the initial state using [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity)

Return the cell and initial state in the following tuple `(Cell, InitialState)`

In [ ]:
def get_init_cell(batch_size, rnn_size):
    """
    Create an RNN Cell and initialize it.
    :param batch_size: Size of batches
    :param rnn_size: Size of RNNs
    :return: Tuple (cell, initialize state)
    """
    # TODO: Implement Function
    lstm = tf.contrib.rnn.BasicLSTMCell(rnn_size)
    #for cell ([lstm]* batch_size) means batch_size num layers of LSTM cells
    # but keep it to 1 or 2 for computational efficiency
    #cell = tf.contrib.rnn.MultiRNNCell([lstm]*2)
    num_layers=2
    cell = tf.contrib.rnn.MultiRNNCell([tf.contrib.rnn.BasicLSTMCell(rnn_size) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    initial_state = tf.identity(initial_state, 'initial_state')
    return (cell, initial_state)

    
    ########################################################################################################
    #cell = tf.contrib.rnn.MultiRNNCell([tf.contrib.rnn.BasicLSTMCell(rnn_size) for _ in range(num_layers)])
    ###########################################################################################################
#################################################################################################################
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_get_init_cell(get_init_cell)

### Word Embedding
Apply embedding to `input_data` using TensorFlow.  Return the embedded sequence.

In [ ]:
############
vocab_size = len(int_to_vocab)
embed_dim = 200 # Number of embedding features 

def get_embed(input_data, vocab_size, embed_dim):
    """
    Create embedding for <input_data>.
    :param input_data: TF placeholder for text input.
    :param vocab_size: Number of words in vocabulary.
    :param embed_dim: Number of embedding dimensions
    :return: Embedded input.
    """
    # TODO: Implement Function
    embedding = tf.Variable(tf.random_uniform((vocab_size, embed_dim), -1, 1))#embedding matrix
    embed = tf.nn.embedding_lookup(embedding, input_data)#embedding tensors
    
    return embed


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_get_embed(get_embed)

### Build RNN
You created a RNN Cell in the `get_init_cell()` function.  Time to use the cell to create a RNN.
- Build the RNN using the [`tf.nn.dynamic_rnn()`](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn)
 - Apply the name "final_state" to the final state using [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity)

Return the outputs and final_state state in the following tuple `(Outputs, FinalState)` 

In [ ]:
###############from https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn
""""tf.nn.dynamic_rnn(
    cell,
    inputs,
    sequence_length=None,
    initial_state=None,
    dtype=None,
    parallel_iterations=None,
    swap_memory=False,
    time_major=False,
    scope=None
)"""
#######################################################################################

def build_rnn(cell, inputs):
    """
    Create a RNN using a RNN Cell
    :param cell: RNN Cell
    :param inputs: Input text data
    :return: Tuple (Outputs, Final State)
    """
    # TODO: Implement Function
    Outputs, final_state = tf.nn.dynamic_rnn(cell, inputs, dtype = tf.float32, initial_state = None)
    FinalState = tf.identity(final_state, 'final_state')
    
    return (Outputs, FinalState)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_build_rnn(build_rnn)

### Build the Neural Network
Apply the functions you implemented above to:
- Apply embedding to `input_data` using your `get_embed(input_data, vocab_size, embed_dim)` function.
- Build RNN using `cell` and your `build_rnn(cell, inputs)` function.
- Apply a fully connected layer with a linear activation and `vocab_size` as the number of outputs.

Return the logits and final state in the following tuple (Logits, FinalState) 

In [ ]:
#!pip install -U tensorflow==1.3
def build_nn(cell, rnn_size, input_data, vocab_size, embed_dim):
    """
    Build part of the neural network
    :param cell: RNN cell
    :param rnn_size: Size of rnns???????????
    :param input_data: Input data
    :param vocab_size: Vocabulary size
    :param embed_dim: Number of embedding dimensions
    :return: Tuple (Logits, FinalState)
    """
    # TODO: Implement Function
    #apply embedding per above
    inputs = get_embed(input_data,vocab_size, embed_dim)
    #build RNN per above
    outputs, final_state = build_rnn(cell, inputs)
    
    #using tensorflow function and None for activation keeps it linear
    logits = tf.contrib.layers.fully_connected(outputs, vocab_size, activation_fn=None)
    
    
    return (logits, final_state)
    

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_build_nn(build_nn)

In [ ]:
""""Batches
Implement `get_batches` to create batches of input and targets using `int_text`.  
The batches should be a Numpy array with the shape `(number of batches, 2, batch size, sequence length)`. 
Each batch contains two elements:
- The first element is a single batch of **input** with the shape `[batch size, sequence length]`
- The second element is a single batch of **targets** with the shape `[batch size, sequence length]`

If you can't fill the last batch with enough data, drop the last batch.

For example, `get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 3, 2)` 
would return a Numpy array of the following:
```
[
  # First Batch
  [
    # Batch of Input
    [[ 1  2], [ 7  8], [13 14]]
    # Batch of targets
    [[ 2  3], [ 8  9], [14 15]]
  ]

  # Second Batch
  [
    # Batch of Input
    [[ 3  4], [ 9 10], [15 16]]
    # Batch of targets
    [[ 4  5], [10 11], [16 17]]
  ]

  # Third Batch
  [
    # Batch of Input
    [[ 5  6], [11 12], [17 18]]
    # Batch of targets
    [[ 6  7], [12 13], [18  1]]
  ]
]
```

Notice that the last target value in the last batch is the first input value of the first batch. In this case, `1`. 
This is a common technique used when creating sequence batches, although it is rather unintuitive."""

In [ ]:
def get_batches(int_text, batch_size, seq_length):#(array, batch_size (number of batches), (1,2,3),(4,5,6)
    """
    Return batches of input and target (shift targets over 1 and wrap around so first input is last target)
    :param int_text: Text with the words replaced by their ids (arr)
    :param batch_size: The size of batch
    :param seq_length: The length of sequence (n_steps)
    :return: Batches as a Numpy array
    """
    
    # TODO: Implement Function
     # Get the number of characters per batch and number of batches we can make
    chars_per_batch = batch_size * seq_length #128 * 5 =640
    n_batches = len(int_text)//chars_per_batch # 7 = 4480/640  probably gets floored to 7
    
    # Keep only enough characters to make full batches
    input_data = np.array(int_text[:n_batches * chars_per_batch])#int_text[:4480]
    ################test code
    #print("int_text")
    #print(int_text)#0 to 4479
    
    #roll over first x to last y
    target_data = np.roll(input_data, -1)#????sure
    
    #reshape and split input and target data
    input_batches = np.split(input_data.reshape(batch_size, -1), n_batches, 1)
    target_batches = np.split(target_data.reshape(batch_size, -1), n_batches, 1)
    
    #zip the above input and target batches
    #refer to https://stackoverflow.com/questions/13704860/zip-lists-in-python
    Batches = np.array(list(zip(input_batches, target_batches)))
    
    return Batches
#TODO:  read numpy and python documentation as a lot of this mimics what I saw in forums

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_get_batches(get_batches)

## Neural Network Training
### Hyperparameters
Tune the following parameters:

- Set `num_epochs` to the number of epochs.
- Set `batch_size` to the batch size.
- Set `rnn_size` to the size of the RNNs.
- Set `embed_dim` to the size of the embedding.
- Set `seq_length` to the length of sequence.
- Set `learning_rate` to the learning rate.
- Set `show_every_n_batches` to the number of batches the neural network should print progress.

In [ ]:
# Number of Epochs
num_epochs = 100
# Batch Size
batch_size = 50
# RNN Size should be more than the embed_dim(hidden layer size, suggested start at double)
rnn_size = 500
# Embedding Dimension Size (hidden layer)
embed_dim = 256
# Sequence Length
seq_length = 50
# Learning Rate
learning_rate = 0.01
# Show stats for every n number of batches
show_every_n_batches = 10
#numbers taken from discussion forums

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
save_dir = './save'

### Build the Graph
Build the graph using the neural network you implemented.

In [ ]:
'''
DON'T MODIFY ANYTHING IN THIS CELL
"""
from tensorflow.contrib import seq2seq
from tensorflow import keras

train_graph = tf.Graph()
with train_graph.as_default():
    vocab_size = len(int_to_vocab)
    input_text, targets, lr = get_inputs()
    input_data_shape = tf.shape(input_text)
    cell, initial_state = get_init_cell(input_data_shape[0], rnn_size)
    logits, final_state = build_nn(cell, rnn_size, input_text, vocab_size, embed_dim)

    # Probabilities for generating words
    probs = tf.nn.softmax(logits, name='probs')

    # Loss function
    cost = seq2seq.sequence_loss(
        logits,
        targets,
        tf.ones([input_data_shape[0], input_data_shape[1]]))

    # Optimizer
    optimizer = tf.train.AdamOptimizer(lr)

    # Gradient Clipping
    gradients = optimizer.compute_gradients(cost)
    capped_gradients = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gradients if grad is not None]
    train_op = optimizer.apply_gradients(capped_gradients)

## Train
Train the neural network on the preprocessed data.  If you have a hard time getting a good loss, check the [forums](https://discussions.udacity.com/) to see if anyone is having the same problem.

In [ ]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
batches = get_batches(int_text, batch_size, seq_length)

with tf.Session(graph=train_graph) as sess:
    sess.run(tf.global_variables_initializer())

    for epoch_i in range(num_epochs):
        state = sess.run(initial_state, {input_text: batches[0][0]})

        for batch_i, (x, y) in enumerate(batches):
            feed = {
                input_text: x,
                targets: y,
                initial_state: state,
                lr: learning_rate}
            train_loss, state, _ = sess.run([cost, final_state, train_op], feed)

            # Show every <show_every_n_batches> batches
            if (epoch_i * len(batches) + batch_i) % show_every_n_batches == 0:
                print('Epoch {:>3} Batch {:>4}/{}   train_loss = {:.3f}'.format(
                    epoch_i,
                    batch_i,
                    len(batches),
                    train_loss))

    # Save Model
    saver = tf.train.Saver()
    saver.save(sess, save_dir)
    print('Model Trained and Saved')

## Save Parameters
Save `seq_length` and `save_dir` for generating a new TV script.

In [ ]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Save parameters for checkpoint
helper.save_params((seq_length, save_dir))

# Checkpoint

In [ ]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import tensorflow as tf
import numpy as np
import helper
import problem_unittests as tests

_, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()
seq_length, load_dir = helper.load_params()

## Implement Generate Functions
### Get Tensors
Get tensors from `loaded_graph` using the function [`get_tensor_by_name()`](https://www.tensorflow.org/api_docs/python/tf/Graph#get_tensor_by_name).  Get the tensors using the following names:
- "input:0"
- "initial_state:0"
- "final_state:0"
- "probs:0"

Return the tensors in the following tuple `(InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)` 

In [ ]:
def get_tensors(loaded_graph):
    """
    Get input, initial state, final state, and probabilities tensor from <loaded_graph>
    :param loaded_graph: TensorFlow graph loaded from file
    :return: Tuple (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)
    """
    # TODO: Implement Function
    #from https://discussions.udacity.com/t/stuck-with-the-get-tensor/234988
    
    InputTensor = loaded_graph.get_tensor_by_name("input:0")
    InitialStateTensor = loaded_graph.get_tensor_by_name("initial_state:0")
    FinalStateTensor = loaded_graph.get_tensor_by_name("final_state:0")
    ProbsTensor = loaded_graph.get_tensor_by_name("probs:0")
    
    return (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)
    


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_tensors(get_tensors)

### Choose Word
Implement the `pick_word()` function to select the next word using `probabilities`.

In [ ]:
def pick_word(probabilities, int_to_vocab):
    """
    Pick the next word in the generated text
    :param probabilities: Probabilites of the next word (list)
    :param int_to_vocab: Dictionary of word ids as the keys and words as the values
    :return: String of the predicted word
    """
    # TODO: Implement Function
    #print(probabilities)
    #print(len(probabilities))
    
    #https://discussions.udacity.com/t/pick-word-passes-test-but-fails-latter/383468
    #probabilities is a list or matrix so just reshape into a vector
    #probabilities = probabilities.reshape((-1))
    #print(probabilities)
    pick = np.random.choice(len(probabilities), p=probabilities)
    #print(pick)
    #print(int_to_vocab[pick])
    return int_to_vocab[pick]
    
    #my pseudocode
    #max of probability[i] is int_to_vocab[i]
    #next_word = int_to_vocab[i]
    #return next_word
    


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_pick_word(pick_word)

## Generate TV Script
This will generate the TV script for you.  Set `gen_length` to the length of TV script you want to generate.

In [ ]:
gen_length = 200
# homer_simpson, moe_szyslak, or Barney_Gumble
prime_word = 'moe_szyslak'

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
loaded_graph = tf.Graph()
with tf.Session(graph=loaded_graph) as sess:
    # Load saved model
    loader = tf.train.import_meta_graph(load_dir + '.meta')
    loader.restore(sess, load_dir)

    # Get Tensors from loaded model
    input_text, initial_state, final_state, probs = get_tensors(loaded_graph)

    # Sentences generation setup
    gen_sentences = [prime_word + ':']
    prev_state = sess.run(initial_state, {input_text: np.array([[1]])})

    # Generate sentences
    for n in range(gen_length):
        # Dynamic Input
        dyn_input = [[vocab_to_int[word] for word in gen_sentences[-seq_length:]]]
        dyn_seq_length = len(dyn_input[0])

        # Get Prediction
        probabilities, prev_state = sess.run(
            [probs, final_state],
            {input_text: dyn_input, initial_state: prev_state})
        
        #pred_word = pick_word(probabilities[dyn_seq_length-1], int_to_vocab)
        #####################adjustments made here based on error and solutions in forum
        temp = np.squeeze(probabilities, axis=0)
        temp = temp[dyn_seq_length - 1]
        pred_word = pick_word(temp, int_to_vocab)

        gen_sentences.append(pred_word)
    
    # Remove tokens
    tv_script = ' '.join(gen_sentences)
    for key, token in token_dict.items():
        ending = ' ' if key in ['\n', '(', '"'] else ''
        tv_script = tv_script.replace(' ' + token.lower(), key)
    tv_script = tv_script.replace('\n ', '\n')
    tv_script = tv_script.replace('( ', '(')
        
    print(tv_script)

# The TV Script is Nonsensical
It's ok if the TV script doesn't make any sense.  We trained on less than a megabyte of text.  In order to get good results, you'll have to use a smaller vocabulary or get more data.  Luckily there's more data!  As we mentioned in the beggining of this project, this is a subset of [another dataset](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data).  We didn't have you train on all the data, because that would take too long.  However, you are free to train your neural network on all the data.  After you complete the project, of course.
# Submitting This Project
When submitting this project, make sure to run all the cells before saving the notebook. Save the notebook file as "dlnd_tv_script_generation.ipynb" and save it as a HTML file under "File" -> "Download as". Include the "helper.py" and "problem_unittests.py" files in your submission.